default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_DATABASE_HOST'] %>
  username: <%= ENV['DB_DATABASE_USER'] %>
  password: <%= ENV['DB_DATABASE_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE_NAME'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>

test:
  <<: *default
  database: 'insta_clone_test'

production:
  <<: *default
